### ISSUE TITLE
Colon in header value causes truncation of value 

### ISSUE THREAD

**Issue by vmaasalo** [igneus/gly#1] opened 2016-04-04 08:36 UTC
I like to use the header "`user-notes`" to give the translation. If the text contains a colon, the value of "`user-notes`" in the produced `gabc` file only contains the text preceding the colon; anything after it is lost.

**Comment by igneus** [comment] 2016-05-09 18:07
Hi, I'm sorry it took me so long to address this tiny issue. I believed I was getting e-mail notification whenever someone opens an issue in my repository, but obviously it's not the case. I will check and adjust my notification settings.

The issue is now fixed in master and will be included in the next gem release. Thanks for reporting it.

**Closed as completed by igneus** 2016-05-09 18:07 UTC

**Comment by vmaasalo** [comment] 2016-05-09 20:16
Thank you, I appreciate it! This project of yours has made using Gregorio so much easier for me.
